---
- name: Quick test showing vault creds
  hosts: vault
  gather_facts: false
  vars:
    
  tasks:
    - name: Issue a command to show everything is working
      shell: hostname
      register: hostname_output

    - name: Display the hostname output
      debug:
        msg: "hostname is {{ hostname_output.stdout }}"

    - name: Display the vault special key
      debug:
        msg: "The vault special key is {{ special_key | default('not set', true) }}"