---
- name: Quick test showing vault creds
  hosts: vault
  gather_facts: false
  vars:
  tasks:
    - name: Just see if we connected successfully
      debug:
        msg: "Connected to vault host successfully"
    
    - name: Quick ping via cli 5 times
      shell: "ping -c 5 {{ item }}"
      loop:
        - command
        - vault
        - vscode
      register: ping_results

    - name: Show ping results
      debug:
        var: ping_results